import { mkdir, readFile, realpath, rm, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute, join } from "node:path";
import { gradientDir, loadManifest } from "./manifest.js";
import { assertInside, sanitizeName } from "./security.js";
import { loadSuggestions } from "../commands/apply.js";
import { emitHook } from "./emit/hook.js";
import type { ManifestEntry } from "./types.js";

export interface BundleResult {
  dir: string;
  files: string[];
  skipped: string[];
}

const BUNDLE_DESCRIPTION = "Workflows mined from real usage by gradient";

async function put(root: string, relativePath: string, content: string, files: string[]): Promise<void> {
  const path = join(root, relativePath);
  assertInside(root, path);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
  files.push(path);
}

async function readApprovedArtifact(projectDir: string, entry: ManifestEntry): Promise<string> {
  const assistantRoot = await realpath(join(projectDir, entry.target === "codex" ? ".agents" : ".claude"));
  const source = isAbsolute(entry.path) ? entry.path : join(projectDir, entry.path);
  const resolvedSource = await realpath(source);
  assertInside(assistantRoot, resolvedSource);
  return readFile(resolvedSource, "utf8");
}

function bundleReadme(name: string, hasRules: boolean, hasHooks: boolean): string {
  return [
    `# ${name}`,
    "",
    "Generated by [gradient](https://gradient.md) from approved, usage-mined artifacts.",
    "Evidence counts are personal telemetry and are deliberately not included.",
    "",
    "Try locally: `claude --plugin-dir <path-to-this-directory>`.",
    "Codex: add this plugin through a local marketplace; `.codex-plugin/plugin.json` is included.",
    ...(hasRules ? [
      "",
      "`rules/`: Claude Code plugins do not auto-load rules. Copy these files into a project's `.claude/rules/`. Codex users should copy equivalent standing guidance into AGENTS.md manually.",
    ] : []),
    ...(hasHooks ? [
      "",
      "`hooks/hooks.json`: these Claude Code hooks call `gradient` subcommands. Teammates need gradient installed (`npx gradient.md`). They are not declared in the Codex manifest.",
    ] : []),
    "",
  ].join("\n");
}

export async function buildBundle(
  projectDir: string,
  name: string,
  opts: { withHooks?: boolean } = {},
): Promise<BundleResult> {
  const safeName = sanitizeName(name);
  const bundlesDir = join(gradientDir(projectDir), "bundle");
  const root = join(bundlesDir, safeName);
  assertInside(gradientDir(projectDir), root);

  // A bundle is a projection of the current manifest, not an incremental
  // cache. Rebuild it so removed artifacts and opt-in hooks cannot linger.
  await rm(root, { recursive: true, force: true });

  const files: string[] = [];
  const skipped: string[] = [];
  let hasRules = false;
  const entries = await loadManifest(projectDir);

  // A dual-target apply records one entry per assistant. Bundle each logical
  // artifact once, preferring the portable Codex skill copy when both exist.
  const artifacts = new Map<string, ManifestEntry>();
  for (const entry of entries) {
    if (entry.type === "hook") continue;
    const key = `${entry.type}\u0000${entry.name}`;
    const existing = artifacts.get(key);
    if (!existing || (entry.type === "skill" && entry.target === "codex")) artifacts.set(key, entry);
  }

  for (const entry of artifacts.values()) {
    if (!entry.path) {
      skipped.push(entry.name);
      continue;
    }
    let content: string;
    try {
      content = await readApprovedArtifact(projectDir, entry);
    } catch {
      skipped.push(entry.name);
      continue;
    }

    const artifactName = sanitizeName(entry.name);
    if (entry.type === "skill") {
      await put(root, join("skills", artifactName, "SKILL.md"), content, files);
    } else if (entry.type === "command") {
      await put(root, join("commands", `${artifactName}.md`), content, files);
      // Codex plugins consume Agent Skills, not legacy Claude commands. The
      // markdown format is compatible, so expose the same approved body as a
      // skill unless an applied skill with that name already won above.
      if (!artifacts.has(`skill\u0000${entry.name}`)) {
        await put(root, join("skills", artifactName, "SKILL.md"), content, files);
      }
    } else if (entry.type === "rule") {
      hasRules = true;
      await put(root, join("rules", basename(entry.path)), content, files);
    } else {
      skipped.push(entry.name);
    }
  }

  let hasHooks = false;
  if (opts.withHooks) {
    const suggestions = await loadSuggestions(projectDir);
    const byId = new Map(suggestions.map(suggestion => [suggestion.id, suggestion]));
    type HookGroup = {
      matcher?: string;
      hooks: Array<{ type: string; command: string }>;
    };
    const hookEvents: Record<string, HookGroup[]> = Object.create(null) as Record<string, HookGroup[]>;

    for (const entry of entries) {
      if (entry.type !== "hook") continue;
      const suggestion = byId.get(entry.suggestionId);
      try {
        if (!suggestion || suggestion.payload.type !== "hook") throw new Error("missing hook suggestion");
        // Reuse the applied-hook emitter as the trust boundary: it rejects
        // unknown lifecycle events and non-gradient subcommands.
        const emitted = JSON.parse(emitHook(suggestion).settingsPatch) as {
          hooks?: Record<string, HookGroup[]>;
        };
        const event = Object.entries(emitted.hooks ?? {})[0];
        if (!event) throw new Error("empty hook patch");
        const [eventName, groups] = event;
        const target = hookEvents[eventName] ?? (hookEvents[eventName] = []);
        for (const group of groups) {
          const command = group.hooks?.[0]?.command;
          if (!command || target.some(existing =>
            existing.hooks[0]?.command === command && existing.matcher === group.matcher,
          )) continue;
          target.push({
            ...(group.matcher ? { matcher: group.matcher } : {}),
            hooks: [{ type: "command", command }],
          });
        }
      } catch {
        skipped.push(entry.name);
      }
    }

    if (Object.keys(hookEvents).length > 0) {
      hasHooks = true;
      await put(root, join("hooks", "hooks.json"), `${JSON.stringify({ hooks: hookEvents }, null, 2)}\n`, files);
    }
  }
  await put(
    root,
    join(".claude-plugin", "plugin.json"),
    `${JSON.stringify({
      name: safeName,
      description: BUNDLE_DESCRIPTION,
      version: "0.1.0",
      author: { name: "gradient" },
    }, null, 2)}\n`,
    files,
  );
  await put(
    root,
    join(".codex-plugin", "plugin.json"),
    `${JSON.stringify({
      name: safeName,
      version: "0.1.0",
      description: BUNDLE_DESCRIPTION,
      author: { name: "gradient" },
      homepage: "https://gradient.md",
      repository: "https://github.com/elliot-ylambda/gradient",
      license: "MIT",
      keywords: ["developer-tools", "workflows", "skills"],
      skills: "./skills/",
      interface: {
        displayName: safeName,
        shortDescription: "Approved workflows mined by gradient",
        longDescription: "Reusable team workflows selected from local coding-assistant usage with personal evidence removed.",
        developerName: "gradient",
        category: "Productivity",
        capabilities: ["Interactive"],
        websiteURL: "https://gradient.md",
        defaultPrompt: ["Use the bundled workflow skills for this project."],
      },
    }, null, 2)}\n`,
    files,
  );
  await put(root, "README.md", bundleReadme(safeName, hasRules, hasHooks), files);

  return { dir: root, files, skipped };
}
