import { randomUUID } from "node:crypto";
import { lstat } from "node:fs/promises";
import { basename, join } from "node:path";
import {
  artifactHasMarker,
  artifactMarker,
  expectedArtifactPath,
  gradientDir,
  loadManifest,
  manifestTarget,
} from "./manifest.js";
import { assertInside, redact, sanitizeName } from "./security.js";
import {
  assertNoSymlinkPath,
  safeReadFile,
  safeRemoveTree,
  safeRename,
  safeWriteFile,
} from "./safeFs.js";
import {
  approvalMatches,
  ARTIFACT_SAFETY_VERSION,
  loadArtifactApprovals,
  type ArtifactApproval,
} from "./approvals.js";
import type { ManifestEntry } from "./types.js";
import { VERSION } from "../version.js";

export interface BundleResult {
  dir: string;
  files: string[];
  skipped: string[];
}

interface PreparedArtifact {
  relativePath: string;
  content: string;
}

const BUNDLE_DESCRIPTION = "Workflows mined from real usage by gradient";
const BUNDLE_ARTIFACT_MAX_BYTES = 256_000;
const BUNDLE_TOTAL_MAX_BYTES = 2_000_000;
const BUNDLE_MAX_ARTIFACTS = 200;
const BUNDLE_OWNER_FILE = ".gradient-bundle.json";

async function put(
  projectDir: string,
  root: string,
  relativePath: string,
  content: string,
  files: string[],
): Promise<void> {
  const path = join(root, relativePath);
  assertInside(root, path);
  await safeWriteFile(projectDir, path, content, { exclusive: true, mode: 0o600 });
  files.push(relativePath);
}

async function readApprovedArtifact(
  projectDir: string,
  entry: ManifestEntry,
  approvals: ArtifactApproval[],
  budget: { bytes: number },
): Promise<string> {
  const source = expectedArtifactPath(projectDir, entry);
  if (!source) throw new Error("artifact is print-only");
  const content = await safeReadFile(projectDir, source, { maxBytes: BUNDLE_ARTIFACT_MAX_BYTES });
  budget.bytes += Buffer.byteLength(content, "utf8");
  if (budget.bytes > BUNDLE_TOTAL_MAX_BYTES) {
    throw Object.assign(new Error(`bundle exceeds ${BUNDLE_TOTAL_MAX_BYTES} byte cap`), { code: "EBUNDLECAP" });
  }
  if (!artifactHasMarker(content, entry)) throw new Error("artifact provenance does not match manifest");
  if (!approvalMatches(approvals, entry, content)) {
    throw new Error("artifact was not approved under the current generator safety contract");
  }
  if (redact(content) !== content) throw new Error("artifact contains sensitive-looking data");
  return content.replace(artifactMarker(entry), "<!-- generated by gradient -->");
}

function bundleReadme(name: string, hasRules: boolean): string {
  return [
    `# ${name}`,
    "",
    "Generated by [gradient](https://gradient.md) from artifacts explicitly approved under its current safety contract.",
    "No raw transcript or cache files, evidence counts, local suggestion IDs, or hooks are copied.",
    "Artifact text can quote or derive from redacted prompts, so review every file before sharing.",
    "Best-effort secret detection is not a DLP guarantee.",
    "",
    "Claude Code: `claude --plugin-dir <path-to-this-directory>`.",
    "Codex: add this directory through a local marketplace; `.codex-plugin/plugin.json` is included.",
    ...(hasRules ? [
      "",
      "`rules/`: plugin rules are not auto-loaded. Review and copy them manually into a project's `.claude/rules/` or equivalent AGENTS.md guidance.",
    ] : []),
    "",
  ].join("\n");
}

function ownerFile(name: string): string {
  return `${JSON.stringify({
    format: 1,
    name,
    generator: "gradient",
    artifactSafetyVersion: ARTIFACT_SAFETY_VERSION,
  }, null, 2)}\n`;
}

function codexPlugin(name: string): string {
  return `${JSON.stringify({
    name,
    version: VERSION,
    description: BUNDLE_DESCRIPTION,
    author: { name: "gradient" },
    homepage: "https://gradient.md",
    repository: "https://github.com/elliot-ylambda/gradient",
    license: "MIT",
    keywords: ["developer-tools", "workflows", "skills"],
    skills: "./skills/",
    interface: {
      displayName: name,
      shortDescription: "Approved workflows mined by gradient",
      longDescription: "Reusable team workflows selected from local coding-assistant usage with personal evidence removed.",
      developerName: "gradient",
      category: "Productivity",
      capabilities: ["Interactive"],
      websiteURL: "https://gradient.md",
      defaultPrompt: ["Use the bundled workflow skills for this project."],
    },
  }, null, 2)}\n`;
}

async function validateExistingBundle(
  projectDir: string,
  root: string,
  name: string,
): Promise<boolean> {
  await assertNoSymlinkPath(projectDir, root);
  try {
    const metadata = await lstat(root);
    if (!metadata.isDirectory()) throw new Error(`refusing to replace non-directory bundle target: ${root}`);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(await safeReadFile(projectDir, join(root, BUNDLE_OWNER_FILE), { maxBytes: 4_096 }));
  } catch {
    throw new Error(`refusing to replace bundle target without Gradient ownership metadata: ${root}`);
  }
  const owner = parsed as Record<string, unknown>;
  if (!owner || typeof owner !== "object" || owner.format !== 1 || owner.generator !== "gradient" || owner.name !== name) {
    throw new Error(`refusing to replace bundle target with invalid Gradient ownership metadata: ${root}`);
  }
  return true;
}

async function prepareArtifacts(
  projectDir: string,
  home: string | undefined,
): Promise<{ prepared: PreparedArtifact[]; skipped: string[]; hasRules: boolean }> {
  const entries = await loadManifest(projectDir);
  const fileEntries = entries.filter(entry => entry.path);
  if (fileEntries.length > BUNDLE_MAX_ARTIFACTS) {
    throw new Error(`bundle exceeds ${BUNDLE_MAX_ARTIFACTS} artifact cap`);
  }
  const approvals = await loadArtifactApprovals(projectDir, home);
  const prepared: PreparedArtifact[] = [];
  const skipped = new Set<string>();
  let hasRules = false;
  const budget = { bytes: 0 };

  // One logical skill ships once. Prefer the portable Codex copy, but fall
  // back to an independently approved Claude copy if the preferred source is
  // missing, changed, sensitive, or legacy-unapproved.
  const skills = new Map<string, ManifestEntry[]>();
  for (const entry of entries.filter(candidate => candidate.type === "skill" && candidate.path)) {
    const list = skills.get(entry.name) ?? [];
    list.push(entry);
    skills.set(entry.name, list);
  }
  for (const [name, choices] of skills) {
    choices.sort((a, b) => Number(manifestTarget(b) === "codex") - Number(manifestTarget(a) === "codex"));
    let content: string | undefined;
    for (const entry of choices) {
      try {
        content = await readApprovedArtifact(projectDir, entry, approvals, budget);
        break;
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "EBUNDLECAP") throw error;
        // Try the other assistant's independently approved copy.
      }
    }
    if (!content) {
      skipped.add(name);
      continue;
    }
    prepared.push({ relativePath: join("skills", name, "SKILL.md"), content });
  }

  for (const entry of entries) {
    if (entry.type === "skill") continue;
    if (!entry.path) {
      skipped.add(entry.name);
      continue;
    }
    let content: string;
    try {
      content = await readApprovedArtifact(projectDir, entry, approvals, budget);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "EBUNDLECAP") throw error;
      skipped.add(entry.name);
      continue;
    }
    if (entry.type === "command") {
      // Do not silently elevate a legacy command into an auto-invokable skill;
      // users must explicitly review/apply a skill target.
      prepared.push({ relativePath: join("commands", `${entry.name}.md`), content });
    } else if (entry.type === "rule") {
      hasRules = true;
      prepared.push({ relativePath: join("rules", basename(entry.path)), content });
    } else {
      skipped.add(entry.name);
    }
  }

  return { prepared, skipped: [...skipped].sort(), hasRules };
}

export async function buildBundle(
  projectDir: string,
  name: string,
  opts: { withHooks?: boolean; home?: string } = {},
): Promise<BundleResult> {
  if (opts.withHooks) {
    throw new Error("bundle hooks are disabled pending a recipient-side consent design");
  }
  const safeName = sanitizeName(name);
  const bundlesDir = join(gradientDir(projectDir), "bundle");
  const root = join(bundlesDir, safeName);
  assertInside(gradientDir(projectDir), root);

  const { prepared, skipped, hasRules } = await prepareArtifacts(projectDir, opts.home);
  const hadExisting = await validateExistingBundle(projectDir, root, safeName);
  const nonce = `${process.pid}-${randomUUID()}`;
  const tempRoot = join(bundlesDir, `.gradient-build-${safeName}-${nonce}`);
  const backupRoot = join(bundlesDir, `.gradient-backup-${safeName}-${nonce}`);
  const relativeFiles: string[] = [];

  try {
    for (const artifact of prepared) {
      await put(projectDir, tempRoot, artifact.relativePath, artifact.content, relativeFiles);
    }
    await put(
      projectDir,
      tempRoot,
      join(".claude-plugin", "plugin.json"),
      `${JSON.stringify({
        name: safeName,
        description: BUNDLE_DESCRIPTION,
        version: VERSION,
        author: { name: "gradient" },
      }, null, 2)}\n`,
      relativeFiles,
    );
    await put(projectDir, tempRoot, join(".codex-plugin", "plugin.json"), codexPlugin(safeName), relativeFiles);
    await put(projectDir, tempRoot, "README.md", bundleReadme(safeName, hasRules), relativeFiles);
    await put(projectDir, tempRoot, BUNDLE_OWNER_FILE, ownerFile(safeName), relativeFiles);
  } catch (error) {
    await safeRemoveTree(projectDir, tempRoot).catch(() => undefined);
    throw error;
  }

  let backedUp = false;
  try {
    if (hadExisting) {
      await safeRename(projectDir, root, backupRoot);
      backedUp = true;
    }
    try {
      await safeRename(projectDir, tempRoot, root);
    } catch (error) {
      if (backedUp) await safeRename(projectDir, backupRoot, root);
      throw error;
    }
    if (backedUp) await safeRemoveTree(projectDir, backupRoot);
  } catch (error) {
    await safeRemoveTree(projectDir, tempRoot).catch(() => undefined);
    throw error;
  }

  return {
    dir: root,
    files: relativeFiles.map(relativePath => join(root, relativePath)),
    skipped,
  };
}
