import { randomUUID } from "node:crypto";
import { lstat } from "node:fs/promises";
import { basename, join } from "node:path";
import {
  artifactHasMarker,
  artifactMarker,
  expectedArtifactPath,
  gradientDir,
  loadManifest,
} from "./manifest.js";
import { assertInside, redact, sanitizeName } from "./security.js";
import {
  assertNoSymlinkPath,
  safeReadFile,
  safeRemoveTree,
  safeRename,
  safeWriteFile,
} from "./safeFs.js";
import {
  approvalMatches,
  ARTIFACT_SAFETY_VERSION,
  loadArtifactApprovals,
  type ArtifactApproval,
} from "./approvals.js";
import type { ManifestEntry } from "./types.js";
import { VERSION } from "../version.js";

export interface BundleResult {
  dir: string;
  files: string[];
  skipped: string[];
}

interface PreparedArtifact {
  entry: ManifestEntry;
  relativePath: string;
  content: string;
}

const BUNDLE_DESCRIPTION = "Workflows mined from real usage by gradient";
const BUNDLE_ARTIFACT_MAX_BYTES = 256_000;
const BUNDLE_TOTAL_MAX_BYTES = 2_000_000;
const BUNDLE_MAX_ARTIFACTS = 200;
const BUNDLE_OWNER_FILE = ".gradient-bundle.json";

async function put(
  projectDir: string,
  root: string,
  relativePath: string,
  content: string,
  files: string[],
): Promise<void> {
  const path = join(root, relativePath);
  assertInside(root, path);
  await safeWriteFile(projectDir, path, content, { exclusive: true, mode: 0o600 });
  files.push(relativePath);
}

async function readApprovedArtifact(
  projectDir: string,
  entry: ManifestEntry,
  approvals: ArtifactApproval[],
): Promise<string> {
  const source = expectedArtifactPath(projectDir, entry);
  if (!source) throw new Error("artifact is print-only");
  const content = await safeReadFile(projectDir, source, { maxBytes: BUNDLE_ARTIFACT_MAX_BYTES });
  if (!artifactHasMarker(content, entry)) throw new Error("artifact provenance does not match manifest");
  if (!approvalMatches(approvals, entry, content)) {
    throw new Error("artifact was not approved under the current generator safety contract");
  }
  // A team bundle is an explicit export boundary. Refuse—not silently copy—an
  // artifact that still contains a recognizable credential or PII pattern.
  if (redact(content) !== content) throw new Error("artifact contains sensitive-looking data");
  // The local opaque suggestion ID is personal provenance, not team content.
  return content.replace(artifactMarker(entry), "<!-- generated by gradient -->");
}

function bundleReadme(name: string, hasRules: boolean): string {
  return [
    `# ${name}`,
    "",
    "Generated by [gradient](https://gradient.md) from artifacts explicitly approved under its current safety contract.",
    "No raw transcript or cache files, evidence counts, local suggestion IDs, or hooks are copied.",
    "Artifact text can quote or derive from redacted prompts, so review every file before sharing.",
    "Best-effort secret detection is not a DLP guarantee.",
    "",
    "Try locally: `claude --plugin-dir <path-to-this-directory>`.",
    ...(hasRules ? [
      "",
      "`rules/`: Claude Code plugins do not auto-load rules. Review and copy these files manually into a project's `.claude/rules/`.",
    ] : []),
    "",
  ].join("\n");
}

function ownerFile(name: string): string {
  return `${JSON.stringify({
    format: 1,
    name,
    generator: "gradient",
    artifactSafetyVersion: ARTIFACT_SAFETY_VERSION,
  }, null, 2)}\n`;
}

async function validateExistingBundle(
  projectDir: string,
  root: string,
  name: string,
): Promise<boolean> {
  await assertNoSymlinkPath(projectDir, root);
  try {
    const metadata = await lstat(root);
    if (!metadata.isDirectory()) throw new Error(`refusing to replace non-directory bundle target: ${root}`);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(await safeReadFile(projectDir, join(root, BUNDLE_OWNER_FILE), { maxBytes: 4_096 }));
  } catch {
    throw new Error(`refusing to replace bundle target without Gradient ownership metadata: ${root}`);
  }
  const owner = parsed as Record<string, unknown>;
  if (!owner || typeof owner !== "object" || owner.format !== 1 || owner.generator !== "gradient" || owner.name !== name) {
    throw new Error(`refusing to replace bundle target with invalid Gradient ownership metadata: ${root}`);
  }
  return true;
}

function artifactDestination(entry: ManifestEntry): string | undefined {
  if (entry.type === "skill") return join("skills", entry.name, "SKILL.md");
  if (entry.type === "command") return join("commands", `${entry.name}.md`);
  if (entry.type === "rule") return join("rules", basename(entry.path));
  return undefined;
}

async function prepareArtifacts(
  projectDir: string,
  home: string | undefined,
): Promise<{ prepared: PreparedArtifact[]; skipped: string[]; hasRules: boolean }> {
  const entries = await loadManifest(projectDir);
  const candidates = entries.filter(entry => entry.path && artifactDestination(entry));
  if (candidates.length > BUNDLE_MAX_ARTIFACTS) {
    throw new Error(`bundle exceeds ${BUNDLE_MAX_ARTIFACTS} artifact cap`);
  }
  const approvals = await loadArtifactApprovals(projectDir, home);
  const prepared: PreparedArtifact[] = [];
  const skipped: string[] = [];
  let totalBytes = 0;
  let hasRules = false;

  for (const entry of entries) {
    const relativePath = artifactDestination(entry);
    if (!entry.path || !relativePath) {
      skipped.push(entry.name);
      continue;
    }
    let content: string;
    try {
      content = await readApprovedArtifact(projectDir, entry, approvals);
    } catch {
      skipped.push(entry.name);
      continue;
    }
    totalBytes += Buffer.byteLength(content, "utf8");
    if (totalBytes > BUNDLE_TOTAL_MAX_BYTES) {
      throw new Error(`bundle exceeds ${BUNDLE_TOTAL_MAX_BYTES} byte cap`);
    }
    if (entry.type === "rule") hasRules = true;
    prepared.push({ entry, relativePath, content });
  }

  return { prepared, skipped, hasRules };
}

export async function buildBundle(
  projectDir: string,
  name: string,
  opts: { withHooks?: boolean; home?: string } = {},
): Promise<BundleResult> {
  if (opts.withHooks) {
    throw new Error("bundle hooks are disabled pending a recipient-side consent design");
  }
  const safeName = sanitizeName(name);
  const bundlesDir = join(gradientDir(projectDir), "bundle");
  const root = join(bundlesDir, safeName);
  assertInside(gradientDir(projectDir), root);

  // Fully validate and read bounded source content before touching a previous
  // good bundle. A malformed repo-local manifest or private ledger therefore
  // cannot turn a rebuild into destructive data loss.
  const { prepared, skipped, hasRules } = await prepareArtifacts(projectDir, opts.home);
  const hadExisting = await validateExistingBundle(projectDir, root, safeName);
  const nonce = `${process.pid}-${randomUUID()}`;
  const tempRoot = join(bundlesDir, `.gradient-build-${safeName}-${nonce}`);
  const backupRoot = join(bundlesDir, `.gradient-backup-${safeName}-${nonce}`);
  const relativeFiles: string[] = [];

  try {
    for (const artifact of prepared) {
      await put(projectDir, tempRoot, artifact.relativePath, artifact.content, relativeFiles);
    }
    await put(
      projectDir,
      tempRoot,
      join(".claude-plugin", "plugin.json"),
      `${JSON.stringify({ name: safeName, description: BUNDLE_DESCRIPTION, version: VERSION }, null, 2)}\n`,
      relativeFiles,
    );
    await put(projectDir, tempRoot, "README.md", bundleReadme(safeName, hasRules), relativeFiles);
    await put(projectDir, tempRoot, BUNDLE_OWNER_FILE, ownerFile(safeName), relativeFiles);
  } catch (error) {
    await safeRemoveTree(projectDir, tempRoot).catch(() => undefined);
    throw error;
  }

  let backedUp = false;
  try {
    if (hadExisting) {
      await safeRename(projectDir, root, backupRoot);
      backedUp = true;
    }
    try {
      await safeRename(projectDir, tempRoot, root);
    } catch (error) {
      if (backedUp) await safeRename(projectDir, backupRoot, root);
      throw error;
    }
    if (backedUp) await safeRemoveTree(projectDir, backupRoot);
  } catch (error) {
    await safeRemoveTree(projectDir, tempRoot).catch(() => undefined);
    throw error;
  }

  return {
    dir: root,
    files: relativeFiles.map(relativePath => join(root, relativePath)),
    skipped,
  };
}
