import { describe, it, expect } from "vitest";
import { filterPrompts, isInjected } from "./filter.js";
import type { Turn } from "./types.js";

const u = (text: string): Turn => ({
  ts: "t", project: "p", role: "user", text, sessionId: "s",
});

describe("isInjected", () => {
  it("flags skill-loader and hook scaffolding", () => {
    expect(isInjected("Base directory for this skill: /x")).toBe(true);
    expect(isInjected("<command-name>/compact</command-name>")).toBe(true);
    expect(isInjected("<system-reminder>do x</system-reminder>")).toBe(true);
    expect(isInjected("Caveat: The messages below were generated")).toBe(true);
    expect(isInjected("[Request interrupted by user]")).toBe(true);
    expect(isInjected("local-command-stdout here")).toBe(true);
  });
  it("keeps genuine prompts", () => {
    expect(isInjected("push and create a pull request")).toBe(false);
  });
  it("keeps genuine prompts that start with a non-injected tag (JSX/HTML/XML)", () => {
    expect(isInjected("<div>why is this broken?</div>")).toBe(false);
    expect(isInjected("<Button> not rendering correctly")).toBe(false);
    expect(isInjected("<config> tag in my xml isn't parsing")).toBe(false);
  });
});

describe("filterPrompts", () => {
  it("drops injected, keeps genuine user prompts", () => {
    const turns = [u("Base directory for this skill: /x"), u("fix the bug"),
                   { ts: "t", project: "p", role: "user", sessionId: "s" } as Turn]; // no text → dropped
    const kept = filterPrompts(turns);
    expect(kept.map(t => t.text)).toEqual(["fix the bug"]);
  });
});

describe("harness-injected wrapper blocks", () => {
  // Measured against 67 real transcripts: 80 task-notification blocks and 9
  // local-command-caveat blocks survived the filter — 46% of the corpus fed to
  // clustering was injected text, not typed prompts.
  it("drops <task-notification> blocks", () => {
    const t = "<task-notification>\n<task-id>a0b2062836</task-id>\n<tool-use-id>toolu_01QV</tool-use-id>\n</task-notification>";
    expect(isInjected(t)).toBe(true);
  });

  it("drops <local-command-caveat> blocks", () => {
    // The existing /^Caveat:/ anchor misses these: the wrapper tag comes first.
    const t = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>";
    expect(isInjected(t)).toBe(true);
  });

  it("still keeps a genuine prompt that merely mentions a notification", () => {
    expect(isInjected("why did the task-notification block show up twice?")).toBe(false);
  });

  it("still keeps ordinary prompts", () => {
    expect(isInjected("Continue.")).toBe(false);
    expect(isInjected("write the implementation plan")).toBe(false);
  });
});
