import type { CommandArtifact, SuggestionDraft } from "../../types";
import { sanitizeName } from "../security";

function oneLine(s: string): string {
  return s.replace(/\s+/g, " ").trim().slice(0, 80);
}

/** Suggestion → the content of a .claude/commands/<name>.md slash command. */
export function emitCommand(s: SuggestionDraft): CommandArtifact {
  const name = sanitizeName(s.name);
  const path = `.claude/commands/${name}.md`;
  // detect.ts sets `title` to the representative prompt, so it doubles as the body.
  const content =
    `---\n` +
    `description: ${oneLine(s.title)}\n` +
    `---\n\n` +
    `${s.title.trim()}\n\n` +
    `<!-- generated by gradient · ${s.evidence.count} repeats across ${s.evidence.sessions} sessions -->\n`;
  return { kind: "command", path, content };
}
