import type { Suggestion } from "../types.js";
import { sanitizeName } from "../security.js";

/** Emit standing instructions without ever mutating the user's global CLAUDE.md. */
export function emitRule(s: Suggestion): { path: string; content: string } | { printed: string } {
  if (s.payload.type !== "rule") throw new Error("emitRule needs a rule payload");
  if (s.payload.target === "user") {
    return {
      printed: `add to ~/.claude/CLAUDE.md (gradient never edits it):\n  ${s.payload.text}`,
    };
  }

  const name = sanitizeName(s.payload.ruleName);
  const title = s.title.replace(/[\r\n]+/g, " ").trim();
  const content =
    `<!-- generated by gradient · remove with: gradient remove ${s.name} -->\n` +
    `# ${title}\n\n${s.payload.text}\n`;
  return { path: `.claude/rules/gradient-${name}.md`, content };
}
